### ISSUE TITLE
[Feature] Choices should be able to "go nowhere"

### ISSUE THREAD

**Issue by Wokarol** [Ibralogue/Ibralogue#51]
**Is your feature request related to a problem? Please describe.**
In my case I execute some logic when user selects a choice with a specific metadata. Therefore I do not have a target conversation in the file.

**Describe the solution you'd like and/or any workarounds to the problem**
There should be some keyword that cause the choice to be ignored. Like for example
```cs
- Sure -> Yes
- No way -> No
- Should I? -> __ ## should-accept
```

**Additional information**
The feature is implemented in #46

**Comment by ibra** [comment]
Resolved in #46
